import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Providers>
          <header className="w-full border-b py-4 bg-white">
            <div className="max-w-6xl mx-auto px-4 flex items-center justify-between">
              <Link href="/" className="font-semibold">Portail</Link>
              <nav className="space-x-4">
                <Link href="/login" className="text-sm text-gray-600">Connexion</Link>
                <Link href="/register" className="text-sm text-gray-600">Inscription</Link>
                <Link href="/dashboard" className="text-sm text-gray-600">Dashboard</Link>
              </nav>
            </div>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
